Thu, 25 Jul 2019 14:29:36 log.py[line:17] DEBUG 读取配置项发生了错误,zone_ddds,出院患者特殊级抗菌药物使用量（累计DDD数）
Thu, 25 Jul 2019 14:29:36 log.py[line:20] ERROR No option '\xe5\x87\xba\xe9\x99\xa2\xe6\x82\xa3\xe8\x80\x85\xe7\x89\xb9\xe6\xae\x8a\xe7\xba\xa7\xe6\x8a\x97\xe8\x8f\x8c\xe8\x8d\xaf\xe7\x89\xa9\xe4\xbd\xbf\xe7\x94\xa8\xe9\x87\x8f\xef\xbc\x88\xe7\xb4\xaf\xe8\xae\xa1ddd\xe6\x95\xb0\xef\xbc\x89' in section: 'zone_ddds'
Traceback (most recent call last):
  File "C:\Users\ipharmacare\newreport\common\configReader.py", line 27, in get
    return self.conf.get(field,key)
  File "C:\Users\ipharmacare\python27\lib\ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
NoOptionError: No option '\xe5\x87\xba\xe9\x99\xa2\xe6\x82\xa3\xe8\x80\x85\xe7\x89\xb9\xe6\xae\x8a\xe7\xba\xa7\xe6\x8a\x97\xe8\x8f\x8c\xe8\x8d\xaf\xe7\x89\xa9\xe4\xbd\xbf\xe7\x94\xa8\xe9\x87\x8f\xef\xbc\x88\xe7\xb4\xaf\xe8\xae\xa1ddd\xe6\x95\xb0\xef\xbc\x89' in section: 'zone_ddds'
Thu, 25 Jul 2019 14:29:38 log.py[line:17] DEBUG 读取配置项发生了错误,zone_ddds,出院患者特殊级抗菌药物使用量（累计DDD数）
Thu, 25 Jul 2019 14:29:38 log.py[line:20] ERROR No option '\xe5\x87\xba\xe9\x99\xa2\xe6\x82\xa3\xe8\x80\x85\xe7\x89\xb9\xe6\xae\x8a\xe7\xba\xa7\xe6\x8a\x97\xe8\x8f\x8c\xe8\x8d\xaf\xe7\x89\xa9\xe4\xbd\xbf\xe7\x94\xa8\xe9\x87\x8f\xef\xbc\x88\xe7\xb4\xaf\xe8\xae\xa1ddd\xe6\x95\xb0\xef\xbc\x89' in section: 'zone_ddds'
Traceback (most recent call last):
  File "C:\Users\ipharmacare\newreport\common\configReader.py", line 27, in get
    return self.conf.get(field,key)
  File "C:\Users\ipharmacare\python27\lib\ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
NoOptionError: No option '\xe5\x87\xba\xe9\x99\xa2\xe6\x82\xa3\xe8\x80\x85\xe7\x89\xb9\xe6\xae\x8a\xe7\xba\xa7\xe6\x8a\x97\xe8\x8f\x8c\xe8\x8d\xaf\xe7\x89\xa9\xe4\xbd\xbf\xe7\x94\xa8\xe9\x87\x8f\xef\xbc\x88\xe7\xb4\xaf\xe8\xae\xa1ddd\xe6\x95\xb0\xef\xbc\x89' in section: 'zone_ddds'
Thu, 25 Jul 2019 15:06:36 log.py[line:17] DEBUG 读取配置项发生了错误,zone_ddds,门诊抗菌药物消耗总克数
Thu, 25 Jul 2019 15:06:36 log.py[line:20] ERROR No option '\xe9\x97\xa8\xe8\xaf\x8a\xe6\x8a\x97\xe8\x8f\x8c\xe8\x8d\xaf\xe7\x89\xa9\xe6\xb6\x88\xe8\x80\x97\xe6\x80\xbb\xe5\x85\x8b\xe6\x95\xb0' in section: 'zone_ddds'
Traceback (most recent call last):
  File "C:\Users\ipharmacare\newreport\common\configReader.py", line 27, in get
    return self.conf.get(field,key)
  File "C:\Users\ipharmacare\python27\lib\ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
NoOptionError: No option '\xe9\x97\xa8\xe8\xaf\x8a\xe6\x8a\x97\xe8\x8f\x8c\xe8\x8d\xaf\xe7\x89\xa9\xe6\xb6\x88\xe8\x80\x97\xe6\x80\xbb\xe5\x85\x8b\xe6\x95\xb0' in section: 'zone_ddds'
Thu, 25 Jul 2019 15:06:47 log.py[line:17] DEBUG 读取配置项发生了错误,zone_ddds,门诊抗菌药物消耗总克数
Thu, 25 Jul 2019 15:06:47 log.py[line:20] ERROR No option '\xe9\x97\xa8\xe8\xaf\x8a\xe6\x8a\x97\xe8\x8f\x8c\xe8\x8d\xaf\xe7\x89\xa9\xe6\xb6\x88\xe8\x80\x97\xe6\x80\xbb\xe5\x85\x8b\xe6\x95\xb0' in section: 'zone_ddds'
Traceback (most recent call last):
  File "C:\Users\ipharmacare\newreport\common\configReader.py", line 27, in get
    return self.conf.get(field,key)
  File "C:\Users\ipharmacare\python27\lib\ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
NoOptionError: No option '\xe9\x97\xa8\xe8\xaf\x8a\xe6\x8a\x97\xe8\x8f\x8c\xe8\x8d\xaf\xe7\x89\xa9\xe6\xb6\x88\xe8\x80\x97\xe6\x80\xbb\xe5\x85\x8b\xe6\x95\xb0' in section: 'zone_ddds'
Thu, 25 Jul 2019 15:06:48 log.py[line:17] DEBUG 读取配置项发生了错误,zone_ddds,门诊抗菌药物消耗总克数
Thu, 25 Jul 2019 15:06:48 log.py[line:20] ERROR No option '\xe9\x97\xa8\xe8\xaf\x8a\xe6\x8a\x97\xe8\x8f\x8c\xe8\x8d\xaf\xe7\x89\xa9\xe6\xb6\x88\xe8\x80\x97\xe6\x80\xbb\xe5\x85\x8b\xe6\x95\xb0' in section: 'zone_ddds'
Traceback (most recent call last):
  File "C:\Users\ipharmacare\newreport\common\configReader.py", line 27, in get
    return self.conf.get(field,key)
  File "C:\Users\ipharmacare\python27\lib\ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
NoOptionError: No option '\xe9\x97\xa8\xe8\xaf\x8a\xe6\x8a\x97\xe8\x8f\x8c\xe8\x8d\xaf\xe7\x89\xa9\xe6\xb6\x88\xe8\x80\x97\xe6\x80\xbb\xe5\x85\x8b\xe6\x95\xb0' in section: 'zone_ddds'
Thu, 25 Jul 2019 15:34:46 log.py[line:17] DEBUG 读取配置项发生了错误,zone_ddds,门诊抗菌药物消耗总克数
Thu, 25 Jul 2019 15:34:46 log.py[line:20] ERROR No option '\xe9\x97\xa8\xe8\xaf\x8a\xe6\x8a\x97\xe8\x8f\x8c\xe8\x8d\xaf\xe7\x89\xa9\xe6\xb6\x88\xe8\x80\x97\xe6\x80\xbb\xe5\x85\x8b\xe6\x95\xb0' in section: 'zone_ddds'
Traceback (most recent call last):
  File "C:\Users\ipharmacare\newreport\common\configReader.py", line 27, in get
    return self.conf.get(field,key)
  File "C:\Users\ipharmacare\python27\lib\ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
NoOptionError: No option '\xe9\x97\xa8\xe8\xaf\x8a\xe6\x8a\x97\xe8\x8f\x8c\xe8\x8d\xaf\xe7\x89\xa9\xe6\xb6\x88\xe8\x80\x97\xe6\x80\xbb\xe5\x85\x8b\xe6\x95\xb0' in section: 'zone_ddds'
Thu, 25 Jul 2019 15:34:48 log.py[line:17] DEBUG 读取配置项发生了错误,zone_ddds,门诊抗菌药物消耗总克数
Thu, 25 Jul 2019 15:34:48 log.py[line:20] ERROR No option '\xe9\x97\xa8\xe8\xaf\x8a\xe6\x8a\x97\xe8\x8f\x8c\xe8\x8d\xaf\xe7\x89\xa9\xe6\xb6\x88\xe8\x80\x97\xe6\x80\xbb\xe5\x85\x8b\xe6\x95\xb0' in section: 'zone_ddds'
Traceback (most recent call last):
  File "C:\Users\ipharmacare\newreport\common\configReader.py", line 27, in get
    return self.conf.get(field,key)
  File "C:\Users\ipharmacare\python27\lib\ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
NoOptionError: No option '\xe9\x97\xa8\xe8\xaf\x8a\xe6\x8a\x97\xe8\x8f\x8c\xe8\x8d\xaf\xe7\x89\xa9\xe6\xb6\x88\xe8\x80\x97\xe6\x80\xbb\xe5\x85\x8b\xe6\x95\xb0' in section: 'zone_ddds'
Thu, 25 Jul 2019 15:35:05 log.py[line:17] DEBUG 读取配置项发生了错误,hospital_doc
Thu, 25 Jul 2019 15:35:05 log.py[line:20] ERROR No section: 'hospital_doc'
Traceback (most recent call last):
  File "C:\Users\ipharmacare\newreport\common\configReader.py", line 50, in getitems
    result=self.conf.items(field)
  File "C:\Users\ipharmacare\python27\lib\ConfigParser.py", line 642, in items
    raise NoSectionError(section)
NoSectionError: No section: 'hospital_doc'
Thu, 25 Jul 2019 15:35:05 log.py[line:17] DEBUG 读取配置项发生了错误,default_doc
Thu, 25 Jul 2019 15:35:05 log.py[line:20] ERROR No section: 'default_doc'
Traceback (most recent call last):
  File "C:\Users\ipharmacare\newreport\common\configReader.py", line 50, in getitems
    result=self.conf.items(field)
  File "C:\Users\ipharmacare\python27\lib\ConfigParser.py", line 642, in items
    raise NoSectionError(section)
NoSectionError: No section: 'default_doc'
Thu, 25 Jul 2019 15:35:05 log.py[line:17] DEBUG 读取配置项发生了错误,ConfigurationItem_doc
Thu, 25 Jul 2019 15:35:05 log.py[line:20] ERROR No section: 'ConfigurationItem_doc'
Traceback (most recent call last):
  File "C:\Users\ipharmacare\newreport\common\configReader.py", line 50, in getitems
    result=self.conf.items(field)
  File "C:\Users\ipharmacare\python27\lib\ConfigParser.py", line 642, in items
    raise NoSectionError(section)
NoSectionError: No section: 'ConfigurationItem_doc'
Thu, 25 Jul 2019 15:35:05 log.py[line:17] DEBUG 读取配置项发生了错误,doc_ddds
Thu, 25 Jul 2019 15:35:05 log.py[line:20] ERROR No section: 'doc_ddds'
Traceback (most recent call last):
  File "C:\Users\ipharmacare\newreport\common\configReader.py", line 50, in getitems
    result=self.conf.items(field)
  File "C:\Users\ipharmacare\python27\lib\ConfigParser.py", line 642, in items
    raise NoSectionError(section)
NoSectionError: No section: 'doc_ddds'
Thu, 25 Jul 2019 15:35:05 log.py[line:17] DEBUG 读取配置项发生了错误,hospitalDoc_ddds
Thu, 25 Jul 2019 15:35:05 log.py[line:20] ERROR No section: 'hospitalDoc_ddds'
Traceback (most recent call last):
  File "C:\Users\ipharmacare\newreport\common\configReader.py", line 50, in getitems
    result=self.conf.items(field)
  File "C:\Users\ipharmacare\python27\lib\ConfigParser.py", line 642, in items
    raise NoSectionError(section)
NoSectionError: No section: 'hospitalDoc_ddds'
Thu, 25 Jul 2019 15:35:05 log.py[line:17] DEBUG 读取配置项发生了错误,hospital_dept
Thu, 25 Jul 2019 15:35:05 log.py[line:20] ERROR No section: 'hospital_dept'
Traceback (most recent call last):
  File "C:\Users\ipharmacare\newreport\common\configReader.py", line 50, in getitems
    result=self.conf.items(field)
  File "C:\Users\ipharmacare\python27\lib\ConfigParser.py", line 642, in items
    raise NoSectionError(section)
NoSectionError: No section: 'hospital_dept'
Thu, 25 Jul 2019 15:35:05 log.py[line:17] DEBUG 读取配置项发生了错误,default_dept
Thu, 25 Jul 2019 15:35:05 log.py[line:20] ERROR No section: 'default_dept'
Traceback (most recent call last):
  File "C:\Users\ipharmacare\newreport\common\configReader.py", line 50, in getitems
    result=self.conf.items(field)
  File "C:\Users\ipharmacare\python27\lib\ConfigParser.py", line 642, in items
    raise NoSectionError(section)
NoSectionError: No section: 'default_dept'
Thu, 25 Jul 2019 15:35:05 log.py[line:17] DEBUG 读取配置项发生了错误,ConfigurationItem_dept
Thu, 25 Jul 2019 15:35:05 log.py[line:20] ERROR No section: 'ConfigurationItem_dept'
Traceback (most recent call last):
  File "C:\Users\ipharmacare\newreport\common\configReader.py", line 50, in getitems
    result=self.conf.items(field)
  File "C:\Users\ipharmacare\python27\lib\ConfigParser.py", line 642, in items
    raise NoSectionError(section)
NoSectionError: No section: 'ConfigurationItem_dept'
Thu, 25 Jul 2019 15:35:05 log.py[line:17] DEBUG 读取配置项发生了错误,dept_ddds
Thu, 25 Jul 2019 15:35:05 log.py[line:20] ERROR No section: 'dept_ddds'
Traceback (most recent call last):
  File "C:\Users\ipharmacare\newreport\common\configReader.py", line 50, in getitems
    result=self.conf.items(field)
  File "C:\Users\ipharmacare\python27\lib\ConfigParser.py", line 642, in items
    raise NoSectionError(section)
NoSectionError: No section: 'dept_ddds'
Thu, 25 Jul 2019 15:35:05 log.py[line:17] DEBUG 读取配置项发生了错误,hospitalDept_ddds
Thu, 25 Jul 2019 15:35:05 log.py[line:20] ERROR No section: 'hospitalDept_ddds'
Traceback (most recent call last):
  File "C:\Users\ipharmacare\newreport\common\configReader.py", line 50, in getitems
    result=self.conf.items(field)
  File "C:\Users\ipharmacare\python27\lib\ConfigParser.py", line 642, in items
    raise NoSectionError(section)
NoSectionError: No section: 'hospitalDept_ddds'
Thu, 25 Jul 2019 15:35:05 log.py[line:17] DEBUG 读取配置项发生了错误,default_group
Thu, 25 Jul 2019 15:35:05 log.py[line:20] ERROR No section: 'default_group'
Traceback (most recent call last):
  File "C:\Users\ipharmacare\newreport\common\configReader.py", line 50, in getitems
    result=self.conf.items(field)
  File "C:\Users\ipharmacare\python27\lib\ConfigParser.py", line 642, in items
    raise NoSectionError(section)
NoSectionError: No section: 'default_group'
Thu, 25 Jul 2019 15:35:05 log.py[line:17] DEBUG 该指标在指标库中不存在,门诊去年同期就诊人次数
Thu, 25 Jul 2019 15:35:05 log.py[line:17] DEBUG 该指标在指标库中不存在,门诊处方人次（排除中药饮片）
Thu, 25 Jul 2019 15:35:06 log.py[line:17] DEBUG 该指标在指标库中不存在,门诊输液总人次
Thu, 25 Jul 2019 15:35:06 log.py[line:17] DEBUG 该指标在指标库中不存在,门诊中药饮片处方人次
Thu, 25 Jul 2019 15:35:06 log.py[line:17] DEBUG 该指标在指标库中不存在,门急诊处方人次
Thu, 25 Jul 2019 15:35:06 log.py[line:17] DEBUG 该指标在指标库中不存在,门诊质子泵使用处方人次
Thu, 25 Jul 2019 15:35:06 log.py[line:17] DEBUG 该指标在指标库中不存在,急诊质子泵使用处方人次
Thu, 25 Jul 2019 15:35:06 log.py[line:17] DEBUG 该指标在指标库中不存在,门诊处方人次
Thu, 25 Jul 2019 15:35:06 log.py[line:17] DEBUG 该指标在指标库中不存在,门诊抗菌药物人次数
Thu, 25 Jul 2019 15:35:06 log.py[line:17] DEBUG 该指标在指标库中不存在,门诊抗菌药物人次数占比(%)
Thu, 25 Jul 2019 16:32:10 log.py[line:17] DEBUG 读取配置项发生了错误,zone_ddds,门诊抗菌药物消耗总克数
Thu, 25 Jul 2019 16:32:10 log.py[line:20] ERROR No option '\xe9\x97\xa8\xe8\xaf\x8a\xe6\x8a\x97\xe8\x8f\x8c\xe8\x8d\xaf\xe7\x89\xa9\xe6\xb6\x88\xe8\x80\x97\xe6\x80\xbb\xe5\x85\x8b\xe6\x95\xb0' in section: 'zone_ddds'
Traceback (most recent call last):
  File "C:\Users\ipharmacare\newreport\common\configReader.py", line 27, in get
    return self.conf.get(field,key)
  File "C:\Users\ipharmacare\python27\lib\ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
NoOptionError: No option '\xe9\x97\xa8\xe8\xaf\x8a\xe6\x8a\x97\xe8\x8f\x8c\xe8\x8d\xaf\xe7\x89\xa9\xe6\xb6\x88\xe8\x80\x97\xe6\x80\xbb\xe5\x85\x8b\xe6\x95\xb0' in section: 'zone_ddds'
Thu, 25 Jul 2019 16:32:11 log.py[line:17] DEBUG 读取配置项发生了错误,zone_ddds,门诊抗菌药物消耗总克数
Thu, 25 Jul 2019 16:32:11 log.py[line:20] ERROR No option '\xe9\x97\xa8\xe8\xaf\x8a\xe6\x8a\x97\xe8\x8f\x8c\xe8\x8d\xaf\xe7\x89\xa9\xe6\xb6\x88\xe8\x80\x97\xe6\x80\xbb\xe5\x85\x8b\xe6\x95\xb0' in section: 'zone_ddds'
Traceback (most recent call last):
  File "C:\Users\ipharmacare\newreport\common\configReader.py", line 27, in get
    return self.conf.get(field,key)
  File "C:\Users\ipharmacare\python27\lib\ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
NoOptionError: No option '\xe9\x97\xa8\xe8\xaf\x8a\xe6\x8a\x97\xe8\x8f\x8c\xe8\x8d\xaf\xe7\x89\xa9\xe6\xb6\x88\xe8\x80\x97\xe6\x80\xbb\xe5\x85\x8b\xe6\x95\xb0' in section: 'zone_ddds'
Thu, 25 Jul 2019 16:33:12 log.py[line:17] DEBUG 读取配置项发生了错误,hospital_doc
Thu, 25 Jul 2019 16:33:12 log.py[line:20] ERROR No section: 'hospital_doc'
Traceback (most recent call last):
  File "C:\Users\ipharmacare\newreport\common\configReader.py", line 50, in getitems
    result=self.conf.items(field)
  File "C:\Users\ipharmacare\python27\lib\ConfigParser.py", line 642, in items
    raise NoSectionError(section)
NoSectionError: No section: 'hospital_doc'
Thu, 25 Jul 2019 16:33:12 log.py[line:17] DEBUG 读取配置项发生了错误,default_doc
Thu, 25 Jul 2019 16:33:12 log.py[line:20] ERROR No section: 'default_doc'
Traceback (most recent call last):
  File "C:\Users\ipharmacare\newreport\common\configReader.py", line 50, in getitems
    result=self.conf.items(field)
  File "C:\Users\ipharmacare\python27\lib\ConfigParser.py", line 642, in items
    raise NoSectionError(section)
NoSectionError: No section: 'default_doc'
Thu, 25 Jul 2019 16:33:12 log.py[line:17] DEBUG 读取配置项发生了错误,ConfigurationItem_doc
Thu, 25 Jul 2019 16:33:12 log.py[line:20] ERROR No section: 'ConfigurationItem_doc'
Traceback (most recent call last):
  File "C:\Users\ipharmacare\newreport\common\configReader.py", line 50, in getitems
    result=self.conf.items(field)
  File "C:\Users\ipharmacare\python27\lib\ConfigParser.py", line 642, in items
    raise NoSectionError(section)
NoSectionError: No section: 'ConfigurationItem_doc'
Thu, 25 Jul 2019 16:33:12 log.py[line:17] DEBUG 读取配置项发生了错误,doc_ddds
Thu, 25 Jul 2019 16:33:12 log.py[line:20] ERROR No section: 'doc_ddds'
Traceback (most recent call last):
  File "C:\Users\ipharmacare\newreport\common\configReader.py", line 50, in getitems
    result=self.conf.items(field)
  File "C:\Users\ipharmacare\python27\lib\ConfigParser.py", line 642, in items
    raise NoSectionError(section)
NoSectionError: No section: 'doc_ddds'
Thu, 25 Jul 2019 16:33:12 log.py[line:17] DEBUG 读取配置项发生了错误,hospitalDoc_ddds
Thu, 25 Jul 2019 16:33:12 log.py[line:20] ERROR No section: 'hospitalDoc_ddds'
Traceback (most recent call last):
  File "C:\Users\ipharmacare\newreport\common\configReader.py", line 50, in getitems
    result=self.conf.items(field)
  File "C:\Users\ipharmacare\python27\lib\ConfigParser.py", line 642, in items
    raise NoSectionError(section)
NoSectionError: No section: 'hospitalDoc_ddds'
Thu, 25 Jul 2019 16:33:12 log.py[line:17] DEBUG 读取配置项发生了错误,hospital_dept
Thu, 25 Jul 2019 16:33:12 log.py[line:20] ERROR No section: 'hospital_dept'
Traceback (most recent call last):
  File "C:\Users\ipharmacare\newreport\common\configReader.py", line 50, in getitems
    result=self.conf.items(field)
  File "C:\Users\ipharmacare\python27\lib\ConfigParser.py", line 642, in items
    raise NoSectionError(section)
NoSectionError: No section: 'hospital_dept'
Thu, 25 Jul 2019 16:33:12 log.py[line:17] DEBUG 读取配置项发生了错误,default_dept
Thu, 25 Jul 2019 16:33:12 log.py[line:20] ERROR No section: 'default_dept'
Traceback (most recent call last):
  File "C:\Users\ipharmacare\newreport\common\configReader.py", line 50, in getitems
    result=self.conf.items(field)
  File "C:\Users\ipharmacare\python27\lib\ConfigParser.py", line 642, in items
    raise NoSectionError(section)
NoSectionError: No section: 'default_dept'
Thu, 25 Jul 2019 16:33:12 log.py[line:17] DEBUG 读取配置项发生了错误,ConfigurationItem_dept
Thu, 25 Jul 2019 16:33:12 log.py[line:20] ERROR No section: 'ConfigurationItem_dept'
Traceback (most recent call last):
  File "C:\Users\ipharmacare\newreport\common\configReader.py", line 50, in getitems
    result=self.conf.items(field)
  File "C:\Users\ipharmacare\python27\lib\ConfigParser.py", line 642, in items
    raise NoSectionError(section)
NoSectionError: No section: 'ConfigurationItem_dept'
Thu, 25 Jul 2019 16:33:12 log.py[line:17] DEBUG 读取配置项发生了错误,dept_ddds
Thu, 25 Jul 2019 16:33:12 log.py[line:20] ERROR No section: 'dept_ddds'
Traceback (most recent call last):
  File "C:\Users\ipharmacare\newreport\common\configReader.py", line 50, in getitems
    result=self.conf.items(field)
  File "C:\Users\ipharmacare\python27\lib\ConfigParser.py", line 642, in items
    raise NoSectionError(section)
NoSectionError: No section: 'dept_ddds'
Thu, 25 Jul 2019 16:33:12 log.py[line:17] DEBUG 读取配置项发生了错误,hospitalDept_ddds
Thu, 25 Jul 2019 16:33:12 log.py[line:20] ERROR No section: 'hospitalDept_ddds'
Traceback (most recent call last):
  File "C:\Users\ipharmacare\newreport\common\configReader.py", line 50, in getitems
    result=self.conf.items(field)
  File "C:\Users\ipharmacare\python27\lib\ConfigParser.py", line 642, in items
    raise NoSectionError(section)
NoSectionError: No section: 'hospitalDept_ddds'
Thu, 25 Jul 2019 16:33:12 log.py[line:17] DEBUG 读取配置项发生了错误,default_group
Thu, 25 Jul 2019 16:33:12 log.py[line:20] ERROR No section: 'default_group'
Traceback (most recent call last):
  File "C:\Users\ipharmacare\newreport\common\configReader.py", line 50, in getitems
    result=self.conf.items(field)
  File "C:\Users\ipharmacare\python27\lib\ConfigParser.py", line 642, in items
    raise NoSectionError(section)
NoSectionError: No section: 'default_group'
Thu, 25 Jul 2019 16:41:34 log.py[line:17] DEBUG 读取配置项发生了错误,hospital_doc
Thu, 25 Jul 2019 16:41:34 log.py[line:20] ERROR No section: 'hospital_doc'
Traceback (most recent call last):
  File "C:\Users\ipharmacare\newreport\common\configReader.py", line 50, in getitems
    result=self.conf.items(field)
  File "C:\Users\ipharmacare\python27\lib\ConfigParser.py", line 642, in items
    raise NoSectionError(section)
NoSectionError: No section: 'hospital_doc'
Thu, 25 Jul 2019 16:41:34 log.py[line:17] DEBUG 读取配置项发生了错误,default_doc
Thu, 25 Jul 2019 16:41:34 log.py[line:20] ERROR No section: 'default_doc'
Traceback (most recent call last):
  File "C:\Users\ipharmacare\newreport\common\configReader.py", line 50, in getitems
    result=self.conf.items(field)
  File "C:\Users\ipharmacare\python27\lib\ConfigParser.py", line 642, in items
    raise NoSectionError(section)
NoSectionError: No section: 'default_doc'
Thu, 25 Jul 2019 16:41:35 log.py[line:17] DEBUG 读取配置项发生了错误,ConfigurationItem_doc
Thu, 25 Jul 2019 16:41:35 log.py[line:20] ERROR No section: 'ConfigurationItem_doc'
Traceback (most recent call last):
  File "C:\Users\ipharmacare\newreport\common\configReader.py", line 50, in getitems
    result=self.conf.items(field)
  File "C:\Users\ipharmacare\python27\lib\ConfigParser.py", line 642, in items
    raise NoSectionError(section)
NoSectionError: No section: 'ConfigurationItem_doc'
Thu, 25 Jul 2019 16:41:35 log.py[line:17] DEBUG 读取配置项发生了错误,doc_ddds
Thu, 25 Jul 2019 16:41:35 log.py[line:20] ERROR No section: 'doc_ddds'
Traceback (most recent call last):
  File "C:\Users\ipharmacare\newreport\common\configReader.py", line 50, in getitems
    result=self.conf.items(field)
  File "C:\Users\ipharmacare\python27\lib\ConfigParser.py", line 642, in items
    raise NoSectionError(section)
NoSectionError: No section: 'doc_ddds'
Thu, 25 Jul 2019 16:41:35 log.py[line:17] DEBUG 读取配置项发生了错误,hospitalDoc_ddds
Thu, 25 Jul 2019 16:41:35 log.py[line:20] ERROR No section: 'hospitalDoc_ddds'
Traceback (most recent call last):
  File "C:\Users\ipharmacare\newreport\common\configReader.py", line 50, in getitems
    result=self.conf.items(field)
  File "C:\Users\ipharmacare\python27\lib\ConfigParser.py", line 642, in items
    raise NoSectionError(section)
NoSectionError: No section: 'hospitalDoc_ddds'
Thu, 25 Jul 2019 16:41:35 log.py[line:17] DEBUG 读取配置项发生了错误,hospital_dept
Thu, 25 Jul 2019 16:41:35 log.py[line:20] ERROR No section: 'hospital_dept'
Traceback (most recent call last):
  File "C:\Users\ipharmacare\newreport\common\configReader.py", line 50, in getitems
    result=self.conf.items(field)
  File "C:\Users\ipharmacare\python27\lib\ConfigParser.py", line 642, in items
    raise NoSectionError(section)
NoSectionError: No section: 'hospital_dept'
Thu, 25 Jul 2019 16:41:35 log.py[line:17] DEBUG 读取配置项发生了错误,default_dept
Thu, 25 Jul 2019 16:41:35 log.py[line:20] ERROR No section: 'default_dept'
Traceback (most recent call last):
  File "C:\Users\ipharmacare\newreport\common\configReader.py", line 50, in getitems
    result=self.conf.items(field)
  File "C:\Users\ipharmacare\python27\lib\ConfigParser.py", line 642, in items
    raise NoSectionError(section)
NoSectionError: No section: 'default_dept'
Thu, 25 Jul 2019 16:41:35 log.py[line:17] DEBUG 读取配置项发生了错误,ConfigurationItem_dept
Thu, 25 Jul 2019 16:41:35 log.py[line:20] ERROR No section: 'ConfigurationItem_dept'
Traceback (most recent call last):
  File "C:\Users\ipharmacare\newreport\common\configReader.py", line 50, in getitems
    result=self.conf.items(field)
  File "C:\Users\ipharmacare\python27\lib\ConfigParser.py", line 642, in items
    raise NoSectionError(section)
NoSectionError: No section: 'ConfigurationItem_dept'
Thu, 25 Jul 2019 16:41:35 log.py[line:17] DEBUG 读取配置项发生了错误,dept_ddds
Thu, 25 Jul 2019 16:41:35 log.py[line:20] ERROR No section: 'dept_ddds'
Traceback (most recent call last):
  File "C:\Users\ipharmacare\newreport\common\configReader.py", line 50, in getitems
    result=self.conf.items(field)
  File "C:\Users\ipharmacare\python27\lib\ConfigParser.py", line 642, in items
    raise NoSectionError(section)
NoSectionError: No section: 'dept_ddds'
Thu, 25 Jul 2019 16:41:35 log.py[line:17] DEBUG 读取配置项发生了错误,hospitalDept_ddds
Thu, 25 Jul 2019 16:41:35 log.py[line:20] ERROR No section: 'hospitalDept_ddds'
Traceback (most recent call last):
  File "C:\Users\ipharmacare\newreport\common\configReader.py", line 50, in getitems
    result=self.conf.items(field)
  File "C:\Users\ipharmacare\python27\lib\ConfigParser.py", line 642, in items
    raise NoSectionError(section)
NoSectionError: No section: 'hospitalDept_ddds'
Thu, 25 Jul 2019 16:41:35 log.py[line:17] DEBUG 读取配置项发生了错误,default_group
Thu, 25 Jul 2019 16:41:35 log.py[line:20] ERROR No section: 'default_group'
Traceback (most recent call last):
  File "C:\Users\ipharmacare\newreport\common\configReader.py", line 50, in getitems
    result=self.conf.items(field)
  File "C:\Users\ipharmacare\python27\lib\ConfigParser.py", line 642, in items
    raise NoSectionError(section)
NoSectionError: No section: 'default_group'
Thu, 25 Jul 2019 16:41:45 log.py[line:17] DEBUG 该指标在指标库中不存在,使用非限制级抗菌药物出院患者中病原学检查送检人次
Thu, 25 Jul 2019 16:41:45 log.py[line:17] DEBUG 该指标在指标库中不存在,使用限制级抗菌药物出院患者中病原学检查送检人次
Thu, 25 Jul 2019 16:41:45 log.py[line:17] DEBUG 该指标在指标库中不存在,使用特殊级抗菌药物出院患者中病原学检查送检人次
Thu, 25 Jul 2019 16:41:45 log.py[line:17] DEBUG 该指标在指标库中不存在,出院患者静脉输液总人次
Thu, 25 Jul 2019 16:41:45 log.py[line:17] DEBUG 该指标在指标库中不存在,出院患者总人次（排除中药饮片）
Thu, 25 Jul 2019 16:41:45 log.py[line:17] DEBUG 该指标在指标库中不存在,出院患者特殊级抗菌药物使用人次数
Thu, 25 Jul 2019 16:41:45 log.py[line:17] DEBUG 该指标在指标库中不存在,出院患者抗菌药物预防使用人次
Thu, 25 Jul 2019 16:41:46 connectionpool.py[line:205] DEBUG Starting new HTTP connection (1): 10.1.1.89:9999
Thu, 25 Jul 2019 16:41:46 connectionpool.py[line:393] DEBUG http://10.1.1.89:9999 "POST /syscenter/api/v1/currentUser HTTP/1.1" 200 None
Thu, 25 Jul 2019 16:41:46 connectionpool.py[line:393] DEBUG http://10.1.1.89:9999 "GET /syscenter/api/v1/config/selectSysConfig?showName=%E6%8A%97%E8%8F%8C%E8%8D%AF%E7%89%A9%E9%80%81%E6%A3%80%E6%A0%87%E8%AF%86 HTTP/1.1" 200 None
Thu, 25 Jul 2019 16:41:53 connectionpool.py[line:205] DEBUG Starting new HTTP connection (1): 10.1.1.89:9999
Thu, 25 Jul 2019 16:41:53 connectionpool.py[line:393] DEBUG http://10.1.1.89:9999 "POST /syscenter/api/v1/currentUser HTTP/1.1" 200 None
Thu, 25 Jul 2019 16:41:53 connectionpool.py[line:393] DEBUG http://10.1.1.89:9999 "GET /syscenter/api/v1/config/selectSysConfig?showName=%E6%8A%97%E8%8F%8C%E8%8D%AF%E7%89%A9%E9%80%81%E6%A3%80%E6%A0%87%E8%AF%86 HTTP/1.1" 200 None
