Tue, 13 Aug 2019 15:38:27 log.py[line:17] DEBUG 数据库连接出错
Tue, 13 Aug 2019 15:38:27 log.py[line:20] ERROR (2003, "Can't connect to MySQL server on '10.1.1.89' (10060)")
Traceback (most recent call last):
  File "C:/Users/ipharmacare/newreport/common/connectDB.py", line 28, in connect
    return MySQLdb.Connect(host=self.host,port=self.port,user=self.username,passwd=self.passwd,db=dbname,charset=self.charset)
  File "C:\Users\ipharmacare\python27\lib\site-packages\MySQLdb\__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "C:\Users\ipharmacare\python27\lib\site-packages\MySQLdb\connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (2003, "Can't connect to MySQL server on '10.1.1.89' (10060)")
Tue, 13 Aug 2019 15:38:27 log.py[line:17] DEBUG 读取配置项发生了错误,zone,出院患者中抗菌药物治疗使用前病原学检查送检人次
Tue, 13 Aug 2019 15:38:27 log.py[line:20] ERROR No option '\xe5\x87\xba\xe9\x99\xa2\xe6\x82\xa3\xe8\x80\x85\xe4\xb8\xad\xe6\x8a\x97\xe8\x8f\x8c\xe8\x8d\xaf\xe7\x89\xa9\xe6\xb2\xbb\xe7\x96\x97\xe4\xbd\xbf\xe7\x94\xa8\xe5\x89\x8d\xe7\x97\x85\xe5\x8e\x9f\xe5\xad\xa6\xe6\xa3\x80\xe6\x9f\xa5\xe9\x80\x81\xe6\xa3\x80\xe4\xba\xba\xe6\xac\xa1' in section: 'zone'
Traceback (most recent call last):
  File "C:\Users\ipharmacare\newreport\common\configReader.py", line 27, in get
    return self.conf.get(field,key)
  File "C:\Users\ipharmacare\python27\lib\ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
NoOptionError: No option '\xe5\x87\xba\xe9\x99\xa2\xe6\x82\xa3\xe8\x80\x85\xe4\xb8\xad\xe6\x8a\x97\xe8\x8f\x8c\xe8\x8d\xaf\xe7\x89\xa9\xe6\xb2\xbb\xe7\x96\x97\xe4\xbd\xbf\xe7\x94\xa8\xe5\x89\x8d\xe7\x97\x85\xe5\x8e\x9f\xe5\xad\xa6\xe6\xa3\x80\xe6\x9f\xa5\xe9\x80\x81\xe6\xa3\x80\xe4\xba\xba\xe6\xac\xa1' in section: 'zone'
